### ISSUE TITLE
Doesn't work on atom v1.16+

### ISSUE THREAD

**Issue by netizen-ais** [Zren/atom-package-manager-commands#8]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 17.04
**Thrown From**: [package-manager-commands](https://github.com/Zren/atom-package-manager-commands) package 2.0.3

### Stack Trace

Uncaught Error: Cannot find module '/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views'

```
At /usr/share/atom/resources/app.asar/src/module-cache.js:379

Error: Cannot find module '/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/package-manager-commands/lib/package-list-view.coffee:1:20)
    at /packages/package-manager-commands/lib/package-list-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.openEnablePackageMenu (/packages/package-manager-commands/lib/main.coffee:115:24)
    at /packages/package-manager-commands/lib/main.coffee:91:92)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at Object.didConfirmSelection (/app.asar/node_modules/command-palette/lib/command-palette-view.js:106:29)
    at SelectListView.confirmSelection (/app.asar/node_modules/atom-select-list/src/select-list-view.js:292:20)
    at /app.asar/node_modules/atom-select-list/src/select-list-view.js:64:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  2x -0:24.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.has-code-annotations-container.theme-laravel-theme.theme-one-dark-ui)
     -0:21.7.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-always.has-code-annotations-container.theme-laravel-theme.theme-one-dark-ui)
     -0:21.7.0 atom-shell-commands:blur (atom-workspace.workspace.scrollbars-visible-always.has-code-annotations-container.theme-laravel-theme.theme-one-dark-ui)
     -0:14.8.0 command-palette:toggle (atom-pane.pane.active)
     -0:12.9.0 core:confirm (input.hidden-input)
     -0:12.9.0 about:view-release-notes (atom-pane.pane.active)
     -0:08.7.0 command-palette:toggle (atom-pane.pane.active)
     -0:07.5.0 core:move-down (input.hidden-input)
     -0:07.3.0 core:confirm (input.hidden-input)
     -0:07.3.0 application:about (atom-pane.pane.active)
     -0:06.3.0 core:close (atom-pane.pane.active)
     -0:05.8.0 command-palette:toggle (atom-pane.pane.active)
     -0:03.7.0 core:confirm (input.hidden-input)
     -0:03.7.0 package-manager:enable-package (atom-pane.pane.active)
```

**Comment by laughedelic** [comment]
Same problem here. Atom 1.18
